[package]
name = "drmod-dbdump"
version.workspace = true
edition = "2024"

[[bin]]
name = "dbdump"
path = "src/main.rs"

[dependencies]
drmod-replay-types = { path = "../drmod-replay-types" }
drmod-script = { path = "../drmod-script" }
rusqlite = { version = "0.40.1", features = ["bundled"] }
csv = "1"
arrow = "59"
parquet = "59"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
