[package]
name = "drmod-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
hudhook = "0.9.0"
imgui = "0.12.0"
windows = {
    version = "0.62.2",
    features = ["Win32_UI_WindowsAndMessaging"]
}
rusqlite = { version = "0.40.1", features = ["bundled"] }
chrono = "0.4.45"

[lib]
crate-type = ["cdylib", "rlib"]
name = "drmod_rs_lib"

[[bin]]
name = "drmod"
path = "src/main.rs"
