using System;
using System.Collections.Generic;

/// One frame of a script, as the command table shows it.
///
/// The shape follows the Rust mod's script format (`docs/API.md` §4.2 in the sibling repo):
/// each stick is described by a direction in degrees plus a deflection magnitude, and every
/// other input is a boolean. Mock data — the frames are generated by <see cref="CommandRows"/>,
/// not read from the on-disk workspace, which is not wired up yet.
sealed record CommandRow(
    int Frame,
    double LeftStickAngle,
    double RightStickAngle,
    double LeftStickAmount,
    double RightStickAmount,
    uint Buttons)
{
    /// Whether the input at `bit` — an index into <see cref="CommandKeys.All"/> — is held on
    /// this frame.
    internal bool Holds(int bit) => (Buttons & (1u << bit)) != 0;
}

/// The boolean inputs a frame can hold, in column order. `Key` is the script's `input` key
/// (`docs/API.md` §4.2), `Label` the 1-2 letter column header that fits an 18 px column.
internal static class CommandKeys
{
    internal static readonly (string Key, string Label)[] All =
    [
        ("forward", "F"),
        ("backward", "B"),
        ("left", "L"),
        ("right", "R"),
        ("jump", "J"),
        ("light_attack", "A"),
        ("heavy_attack", "H"),
        ("ripper", "RP"),
        ("blade", "BL"),
        ("ninja_run", "NR"),
        ("walk", "WK"),
        ("dodge", "DG"),
        ("lock_on", "LK"),
        ("subweapon", "SW"),
        ("item", "IT"),
        ("ar_mode", "AR"),
        ("weapon_select", "WS"),
        ("codec", "CD"),
        ("zandatsu", "ZD"),
        ("camera_reset", "CR"),
        ("pause", "PS"),
        ("confirm", "OK"),
        ("menu_up", "MU"),
        ("menu_down", "MD"),
        ("menu_left", "ML"),
        ("menu_right", "MR"),
    ];

    /// The bit mask for a set of `input` keys, e.g. `Mask("forward", "ninja_run")`. Throws on
    /// an unknown key rather than silently shifting out of range — a typo in the phase table
    /// below would otherwise just light up the wrong column.
    internal static uint Mask(params string[] keys)
    {
        var mask = 0u;
        foreach (var key in keys)
        {
            var bit = IndexOf(key);
            if (bit < 0) throw new ArgumentException($"Unknown input key '{key}'.", nameof(keys));
            mask |= 1u << bit;
        }
        return mask;
    }

    static int IndexOf(string key)
    {
        for (var bit = 0; bit < All.Length; bit++)
        {
            if (All[bit].Key == key) return bit;
        }
        return -1;
    }
}

/// Mock frames for one script: a plausible command list expanded to one row per frame.
///
/// Deterministic — the same script id and frame count always produce the same rows, so the
/// table is reviewable and the tests can assert on its shape. This is the piece the on-disk
/// workspace will replace; the table reads whatever these rows say.
internal static class CommandRows
{
    internal static IReadOnlyList<CommandRow> For(ScriptEntry script)
    {
        var rows = new CommandRow[script.Frames];
        var random = new Random(Seed(script.Id));

        // The sticks are carried from frame to frame: a direction is left where the last turn
        // put it while the stick is at rest, and only the magnitude drops to zero — which is
        // what a hand-written script looks like in the table.
        var leftAngle = 270.0;
        var rightAngle = 0.0;

        var frame = 0;
        var first = true;
        while (frame < rows.Length)
        {
            var phase = first ? Phases[0] : NextPhase(random);
            first = false;

            var last = Math.Min(frame + random.Next(phase.MinFrames, phase.MaxFrames + 1), rows.Length);
            for (; frame < last; frame++)
            {
                leftAngle = Turn(leftAngle, phase.LeftTurn);
                rightAngle = Turn(rightAngle, phase.RightTurn);
                rows[frame] = new CommandRow(
                    frame, leftAngle, rightAngle, phase.LeftAmount, phase.RightAmount, phase.Buttons);
            }
        }

        return rows;
    }

    /// One phase of the mock script: how long it lasts (frames), what it holds, and how far
    /// it turns each stick per frame (degrees).
    readonly record struct Phase(
        int Weight,
        int MinFrames,
        int MaxFrames,
        uint Buttons,
        double LeftAmount,
        double LeftTurn,
        double RightAmount,
        double RightTurn);

    // Weight is the share of the timeline a phase gets (per-mille). The mix is what a real
    // script looks like: long runs carry it, taps are two or three frames, the camera sweeps
    // between fights, and the menu steps only appear around a restart.
    static readonly Phase[] Phases =
    [
        //  weight  frames      inputs                    left  Lturn  right Rturn
        new( 240,   120, 400, CommandKeys.Mask("forward", "ninja_run"), 1.00,  0.0,  0.00,  0.0),
        new(  90,    40, 120, CommandKeys.Mask("forward", "ninja_run"), 1.00,  1.4,  0.00,  0.0),
        new(  90,    40, 120, CommandKeys.Mask("forward", "ninja_run"), 1.00, -1.4,  0.00,  0.0),
        new(  60,     3,   6, CommandKeys.Mask("forward", "ninja_run", "jump"), 1.00, 0.0, 0.00, 0.0),
        new(  40,    60, 200, CommandKeys.Mask("forward", "walk"),      0.50,  0.0,  0.00,  0.0),
        new(  70,     2,   3, CommandKeys.Mask("light_attack"),         0.60,  0.0,  0.00,  0.0),
        new(  60,     2,   5, CommandKeys.Mask("heavy_attack"),         0.60,  0.0,  0.00,  0.0),
        new(  80,    20,  90, CommandKeys.Mask("blade"),                0.40,  0.0,  0.00,  0.0),
        new(  25,     1,   1, CommandKeys.Mask("ripper"),               1.00,  0.0,  0.00,  0.0),
        new(  30,     2,   2, CommandKeys.Mask("dodge"),                0.80,  0.0,  0.00,  0.0),
        new(  30,     8,  20, CommandKeys.Mask("zandatsu"),             0.50,  0.0,  0.00,  0.0),
        new(  25,     2,   2, CommandKeys.Mask("subweapon"),            0.30,  0.0,  0.00,  0.0),
        new(  70,    20,  80, CommandKeys.Mask(),                       0.00,  0.0,  0.80,  2.5),
        new(  70,    20,  80, CommandKeys.Mask(),                       0.00,  0.0,  0.80, -2.5),
        new( 120,     4,  25, CommandKeys.Mask(),                       0.00,  0.0,  0.00,  0.0),
        new(  14,     2,   2, CommandKeys.Mask("pause"),                0.00,  0.0,  0.00,  0.0),
        new(  14,     2,   2, CommandKeys.Mask("confirm"),              0.00,  0.0,  0.00,  0.0),
        new(  14,     3,   3, CommandKeys.Mask("menu_up"),              0.00,  0.0,  0.00,  0.0),
        new(  14,     3,   3, CommandKeys.Mask("menu_down"),            0.00,  0.0,  0.00,  0.0),
    ];

    static readonly int TotalWeight = SumWeights();

    static int SumWeights()
    {
        var total = 0;
        foreach (var phase in Phases) total += phase.Weight;
        return total;
    }

    static Phase NextPhase(Random random)
    {
        var roll = random.Next(TotalWeight);
        foreach (var phase in Phases)
        {
            if (roll < phase.Weight) return phase;
            roll -= phase.Weight;
        }
        return Phases[^1];
    }

    /// Keeps the angle in [0, 360) — the range the table displays it in. A zero turn leaves
    /// the angle alone rather than snapping it to zero: a released stick keeps its direction.
    static double Turn(double angle, double turn) =>
        turn == 0 ? angle : ((angle + turn) % 360 + 360) % 360;

    /// Stable across processes, unlike `string.GetHashCode`, which is randomized per run —
    /// the mock has to look the same every time the app starts.
    static int Seed(string id)
    {
        var seed = 17;
        foreach (var character in id) seed = seed * 31 + character;
        return seed & 0x7FFFFFFF;
    }
}
